// <auto-generated />
namespace MVCMovie.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class unknown : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unknown));
        
        string IMigrationMetadata.Id
        {
            get { return "201703210602511_unknown"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
