//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMovie.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCMovie.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about:blank.
        /// </summary>
        public static string BlankUrl {
            get {
                return ResourceManager.GetString("BlankUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Invalid {0} model..
        /// </summary>
        public static string InvlidModel {
            get {
                return ResourceManager.GetString("InvlidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Invalid site ID..
        /// </summary>
        public static string InvlidSiteID {
            get {
                return ResourceManager.GetString("InvlidSiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.txt.
        /// </summary>
        public static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \log.
        /// </summary>
        public static string LogFolder {
            get {
                return ResourceManager.GetString("LogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster.
        /// </summary>
        public static string Monster {
            get {
                return ResourceManager.GetString("Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented.
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! The {0} information has been saved..
        /// </summary>
        public static string SaveSuccessMsg {
            get {
                return ResourceManager.GetString("SaveSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-Net.
        /// </summary>
        public static string TNet {
            get {
                return ResourceManager.GetString("TNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.bctechnology.com/jobs/search-results.cfm.
        /// </summary>
        public static string TNetUrl {
            get {
                return ResourceManager.GetString("TNetUrl", resourceCulture);
            }
        }
    }
}
