//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMovie.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ElementSelector {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElementSelector() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCMovie.Resources.ElementSelector", typeof(ElementSelector).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must click the company name under the job1.
        /// </summary>
        public static string CompanyTipMsg {
            get {
                return ResourceManager.GetString("CompanyTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go up from the Job1 node to find the link node for Job1.
        /// </summary>
        public static string Job1LinkTipMsg {
            get {
                return ResourceManager.GetString("Job1LinkTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click one of the jobs listed above and choose Job1. This will set this input box automatically.
        /// </summary>
        public static string Job1TipMsg {
            get {
                return ResourceManager.GetString("Job1TipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click  a different job than job 1 in the job list above so that the system will be able to get all the jobs in the list.
        /// </summary>
        public static string Job2TipMsg {
            get {
                return ResourceManager.GetString("Job2TipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click the next link. This will make the system know how to get the next page.
        /// </summary>
        public static string NextTipMsg {
            get {
                return ResourceManager.GetString("NextTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will give the other information, such as, the job location. Must click the other information under Job1 .
        /// </summary>
        public static string OthersTipMsg {
            get {
                return ResourceManager.GetString("OthersTipMsg", resourceCulture);
            }
        }
    }
}
