// <auto-generated />
namespace MVCMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddOneToMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOneToMany));
        
        string IMigrationMetadata.Id
        {
            get { return "201703220539586_AddOneToMany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
